# Generated by Django 2.2.1 on 2019-05-14 10:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_text', models.CharField(max_length=200)),
                ('chore_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chore_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(default=datetime.datetime.now)),
                ('chore', models.ManyToManyField(to='chores.Chore')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
