# Generated by Django 2.2.1 on 2019-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_points',
            field=models.IntegerField(default=5),
        ),
    ]
